# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63bf3c36d3bc9c3ec44d2b7b7a6b4fcc2da08ae1ff86e46576996d80048bb640c17fd5a79d01f4f4205adc51456ce92778e600e2a657bdf08f0db10c1c79e8a

test:
  secret_key_base: c88c0f110854f2f9aee434ffa348dbae46b0e425ac423d777991a04ee305ef713ad85ef8c9246dc707970dc1e527a357470931f79f38639e8d492d84ae282aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
